name: Workflow CI & Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Check Environment
      run: |
        echo "Python version:"
        python --version
        echo "Project structure:"
        ls -R

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow
        pip install -r requirements.txt

    - name: Validate MLflow Project
      run: |
        ls -l
        cat MLproject

    - name: Run MLflow Project
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Model_tracking_asah.mlflow
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-artifacts
        path: MLProject/*

    - name: Debug Model Output
      run: |
        ls -R

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image from MLflow Model
      run: |
        mlflow models build-docker \
          -m model_output_lokal \
          -n ${{ secrets.DOCKER_USERNAME }}/submission-mlops:latest

    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/submission-mlops:latest \
                   ${{ secrets.DOCKER_USERNAME }}/submission-mlops:${{ github.run_id }}

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-mlops:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-mlops:${{ github.run_id }}

    - name: Complete Job
      run: echo "CI/CD Pipeline Completed Successfully"
